export const Boog75Constant = {
    KEY_TOTAL: 81,//81
    LIGHT_ON: 1,
    LIGHT_OFF: 0,
    
    LIGHT_SPEED_MAX: 3,
    LIGHT_SPEED_MIN: 0,
    LIGHT_SPEED_DEFAULT: 2,

    LIGHT_BRIGHTNESS_MAX: 9,
    LIGHT_BRIGHTNESS_MIN: 0,
    LIGHT_BRIGHTNESS_DEFAULT: 9,

    LIGHT_EFFECT_SPECTRAL_CYCLE: 0, // 光谱循环灯
    LIGHT_EFFECT_STATIC: 1, // 常亮
    LIGHT_EFFECT_L_R_SURF: 2, // 左右冲浪灯
    LIGHT_EFFECT_BREATH: 3, // 呼吸灯
    LIGHT_EFFECT_SNAKE: 4, // 往中间蛇行
    LIGHT_EFFECT_MAGNETIC: 5, // 磁力辐射
    LIGHT_EFFECT_ROTATE: 6, // 旋转灯
    LIGHT_EFFECT_M_SURF: 7, // 往中冲浪灯
    LIGHT_EFFECT_COLORFUL_FOUNTAIN: 8, // 七彩喷泉
    LIGHT_EFFECT_LASER: 9, // 按键激光
    LIGHT_EFFECT_CROSS_SURF: 10, // 交叉冲浪
    LIGHT_EFFECT_TRAFFIC: 11, // 交通
    LIGHT_EFFECT_RIPPLING: 12, // 涟漪灯
    LIGHT_EFFECT_DANCE_MACABRE: 13, // 群魔乱舞
    LIGHT_EFFECT_RAND_FOUNTATIN: 14, // 随机喷泉
    LIGHT_EFFECT_LOVE: 15, // 爱心

    LIGHT_EFFECT_DEFAULT: 1,

    RAPID_TRIGGER_MIN: 1,
    RAPID_TRIGGER_MAX: 40,
    RAPID_TRIGGER_STEP: 1,
    RAPID_TRIGGER_DEFAULT: 16,

    CIRCLE_COLOR: ["#f44336", "#e91e63", "#9c27b0", "#673ab7", "#3f51b5", "#2196f3", "#03a9f4", "#00bcd4", "#009688", "#4caf50", "#8bc34a", "#cddc39", "#ffeb3b", "#ffc107", "#ff9800", "#ff5722", "#795548", "#607d8b"],

    MAX_MACRO: 40,
    MAX_PROFILE: 3,
    MAX_ADVANCED_KEY: 20,

    TRIGGER_MODE_NORMAL_1: 0x00,
    TRIGGER_MODE_NORMAL_2: 0x01,
    TRIGGER_MODE_NORMAL_3: 0x02,
    TRIGGER_MODE_TGL: 0x04,
    TRIGGER_MODE_RAPID1: 0x05,
    TRIGGER_MODE_RAPID2: 0x06,

    DKS_MODE_MT: 0x00,
    DKS_MODE_MULTI_KEY: 0x01,
    DKS_MODE_RS:0x02,
    DKS_MODE_ST:0x01,
    DKS_MODE_FULL: 0x03

}





